version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local_traccar
      - MYSQL_USER=traccar
      - MYSQL_PASSWORD=traccar
    expose:
      - 3306
    volumes:
      - mysql-traccar-datavolume:/var/lib/mysql

  traccar:
    image: traccar/traccar:latest
    depends_on:
      - mysql
    volumes:
      - ./traccar/logs:/opt/traccar/logs
      - ./traccar/data:/opt/traccar/data
      - ./traccar/config/traccar.xml:/opt/traccar/config/traccar.xml

    ports:
      - "8082:8082"
      - "5000-5150:5000-5150"
      - "5000-5150:5000-5150/udp"

volumes:
  mysql-traccar-datavolume: